on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

name: lint

jobs:
  lint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: Query dependencies
        run: |
          update.packages(ask = FALSE, checkBuilt = FALSE)
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-3.6-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-3.6-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          # remotes::install_cran("lintr")
        shell: Rscript {0}

      - name: Configure Git user
        run: |
          git config --global user.email "ghau@example.com"
          git config --global user.name "GitHub Actions User"

      - name: Lint
        run: lintr::lint_package()
        shell: Rscript {0}
